CREATE TABLE IF NOT EXISTS `t_macro_release_calendar` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_key` CHAR(40) NOT NULL,
  `source_id` VARCHAR(64) NOT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `indicator_code` VARCHAR(64) NOT NULL,
  `indicator_name` VARCHAR(128) NOT NULL,
  `period_label` VARCHAR(64) NOT NULL,
  `release_title` TEXT NOT NULL,
  `release_at_utc` DATETIME NOT NULL,
  `release_at_taipei` DATETIME NOT NULL,
  `release_timezone` VARCHAR(64) NOT NULL DEFAULT 'America/New_York',
  `importance` TINYINT NOT NULL DEFAULT 3,
  `reminder_date_taipei` DATE NOT NULL,
  `reminder_pushed` TINYINT(1) NOT NULL DEFAULT 0,
  `reminder_pushed_at` DATETIME NULL,
  `reminder_push_status` VARCHAR(32) NULL,
  `reminder_push_error` TEXT NULL,
  `source_url` TEXT NOT NULL,
  `raw_json` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_macro_release_event_key` (`event_key`),
  KEY `idx_macro_release_reminder` (`reminder_date_taipei`, `reminder_pushed`),
  KEY `idx_macro_release_time` (`release_at_taipei`),
  KEY `idx_macro_release_indicator` (`indicator_code`, `release_at_taipei`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
