"""Taiwan topic registry for deterministic article classification."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TopicSpec:
    topic_id: str
    label: str
    primary: tuple[str, ...]
    supporting: tuple[str, ...]
    exclude: tuple[str, ...] = ()
    min_score: float = 1.0
    categories: tuple[str, ...] = ()


GENERAL_SOCIAL_TOPIC_ID = "general_social_news"
GENERAL_SOCIAL_TOPIC_LABEL = "一般社會新聞"
GENERAL_POLITICS_TOPIC_ID = "general_politics_news"
GENERAL_POLITICS_TOPIC_LABEL = "一般政治新聞"


def general_social_topic(
    *,
    source: str = "rule_fallback",
    reason: str = "no_specific_topic_match",
    score: float = 0.0,
    **extra: object,
) -> dict[str, object]:
    """Return the temporary fallback topic for articles without a specific issue hit."""
    return general_topic_for_category(
        "society",
        source=source,
        reason=reason,
        score=score,
        **extra,
    )


def general_politics_topic(
    *,
    source: str = "rule_fallback",
    reason: str = "no_specific_topic_match",
    score: float = 0.0,
    **extra: object,
) -> dict[str, object]:
    """Return the temporary fallback topic for politics articles without a specific issue hit."""
    return general_topic_for_category(
        "politics",
        source=source,
        reason=reason,
        score=score,
        **extra,
    )


def general_topic_for_category(
    category: str | None,
    *,
    source: str = "rule_fallback",
    reason: str = "no_specific_topic_match",
    score: float = 0.0,
    **extra: object,
) -> dict[str, object]:
    normalized = (category or "").strip().lower()
    if normalized == "politics":
        topic_id = GENERAL_POLITICS_TOPIC_ID
        label = GENERAL_POLITICS_TOPIC_LABEL
    else:
        topic_id = GENERAL_SOCIAL_TOPIC_ID
        label = GENERAL_SOCIAL_TOPIC_LABEL
    payload: dict[str, object] = {
        "topic_id": topic_id,
        "label": label,
        "score": round(float(score), 2),
        "source": source,
        "reason": reason,
    }
    payload.update(extra)
    return payload


TOPIC_REGISTRY: list[TopicSpec] = [
    TopicSpec(
        topic_id="drunk_driving_accident",
        label="酒駕毒駕／車禍傷亡",
        primary=(
            "酒駕",
            "毒駕",
            "車禍",
            "肇事",
            "肇逃",
            "撞死",
            "撞傷",
            "翻車",
            "追撞",
            "連撞",
            "對撞",
            "碰撞",
            "衝撞",
            "猛撞",
            "擦撞",
            "撞飛",
            "撞斷",
            "撞上",
            "撞擊",
            "闖紅燈",
            "駕駛肇事",
            "酒測",
            "毒品駕車",
        ),
        supporting=(
            "駕駛",
            "路口",
            "斑馬線",
            "行人",
            "機車",
            "貨車",
            "客運",
            "公車",
            "國道",
            "騎士",
            "乘客",
            "肇責",
            "超速",
            "闖燈",
            "車禍現場",
            "死亡車禍",
            "重傷",
            "奪命",
            "身亡",
            "不治",
            "送醫",
            "頭部重創",
            "夾困",
            "摔落",
            "骨折",
        ),
        exclude=(
            "賽車",
            "電動車補貼",
            "停車費",
            "駕照補助",
            "考機車駕照",
            "科技執法",
            "模型車",
            "玩具車",
        ),
    ),
    TopicSpec(
        topic_id="fraud",
        label="詐騙",
        primary=(
            "詐騙",
            "詐欺",
            "假投資",
            "假交友",
            "車手",
            "詐團",
            "詐騙集團",
            "解除分期",
            "假檢察官",
            "一頁式廣告",
            "投資詐騙",
        ),
        supporting=(
            "被騙",
            "投資群組",
            "假冒",
            "簡訊詐",
            "ATM",
            "匯款",
            "遭詐",
            "報案",
            "防詐",
            "識詐",
        ),
        exclude=(
            "電影",
            "小說",
            "詐騙片",
            "劇情",
        ),
    ),
    TopicSpec(
        topic_id="low_birthrate",
        label="少子化",
        primary=(
            "少子化",
            "\u5c11\u5b50\u5973\u5316",
            "出生率",
            "生育率",
            "生育補助",
            "育兒津貼",
            "催生",
            "\u570b\u5bb6\u4e00\u8d77\u990a",
            "0\u52306\u6b72\u570b\u5bb6\u4e00\u8d77\u990a",
            "\u5152\u5c11TISA",
            "人口負成長",
            "新生兒數",
            "出生人數",
        ),
        supporting=(
            "托育",
            "幼兒園",
            "托嬰",
            "孕婦",
            "新生兒",
            "育嬰假",
            "生育意願",
            "不婚",
            "不生",
            "人口危機",
        ),
        exclude=(
            "移民人口",
            "外籍配偶人數統計",
        ),
    ),
    TopicSpec(
        topic_id="judicial_injustice",
        label="司法量刑不公",
        primary=(
            "量刑",
            "輕判",
            "無罪",
            "司法不公",
            "恐龍法官",
            "司法已死",
            "判決爭議",
            "緩刑爭議",
            "死刑執行",
        ),
        supporting=(
            "法官",
            "檢察官",
            "上訴",
            "緩刑",
            "易科罰金",
            "民怨",
            "判決",
            "起訴",
            "不起訴",
            "輿論譁然",
        ),
        exclude=(
            "民事賠償",
            "離婚訴訟",
            "商業糾紛",
            "勞資爭議",
            "專利訴訟",
        ),
    ),
    TopicSpec(
        topic_id="healthcare_burden",
        label="醫護過勞／醫療崩潰",
        primary=(
            "醫護",
            "護理師",
            "急診壅塞",
            "醫療人力",
            "住院醫師",
            "醫師過勞",
            "護理荒",
            "醫療崩潰",
            "急診人力",
        ),
        supporting=(
            "過勞",
            "罷工",
            "離職潮",
            "輪班",
            "短缺",
            "排班",
            "血汗",
            "缺額",
            "醫療量能",
            "醫護出走",
        ),
        exclude=(
            "護理之家",
            "安養",
            "長照機構",
        ),
    ),
    TopicSpec(
        topic_id="housing_justice",
        label="高房價／居住正義",
        primary=(
            "房價",
            "囤房",
            "房屋稅",
            "社會住宅",
            "租金補貼",
            "炒房",
            "居住正義",
            "房價所得比",
            "買不起房",
        ),
        supporting=(
            "租屋",
            "首購",
            "房貸",
            "建商",
            "預售屋",
            "地價",
            "空屋",
            "包租代管",
            "青年住宅",
        ),
        exclude=(
            "商辦",
            "工業用地",
            "農地買賣",
            "商業不動產",
        ),
    ),
    TopicSpec(
        topic_id="drug_abuse",
        label="新興毒品／校園毒品",
        primary=(
            "新興毒品",
            "校園毒品",
            "毒品濫用",
            "K他命",
            "安非他命",
            "大麻",
            "毒咖啡包",
            "電子煙毒品",
            "喪屍煙彈",
            "喪屍菸彈",
            "毒品煙彈",
            "毒品菸彈",
            "依托咪酯",
            "依托咪酯酸",
            "販毒",
            "絕命毒師",
            "製毒",
            "製造毒品",
            "製毒工廠",
            "製毒技術",
            "第三級毒品",
            "三級毒品",
            "第二級毒品",
            "二級毒品",
            "2級毒品",
            "毒品原料",
            "校園製毒",
        ),
        supporting=(
            "吸毒",
            "施用毒品",
            "查獲毒品",
            "毒品交易",
            "緝毒",
            "戒毒",
            "青少年毒品",
            "毒品氾濫",
            "喵喵",
            "毒品成品",
            "毒品半成品",
        ),
        exclude=(
            "毒駕",
            "毒品電影",
        ),
    ),
]


TOPIC_REGISTRY.extend(
    [
        TopicSpec(
            topic_id="elections",
            label="選舉與投票",
            primary=(
                "選舉",
                "總統大選",
                "立委選舉",
                "地方選舉",
                "補選",
                "罷免",
                "公投",
                "提名",
                "競選",
                "開票",
                "民調",
            ),
            supporting=(
                "候選人",
                "選民",
                "投票",
                "政見",
                "造勢",
                "選戰",
                "初選",
                "選委會",
            ),
            exclude=(
                "董監改選",
                "理事長改選",
                "班級選舉",
            ),
            categories=("politics",),
        ),
        TopicSpec(
            topic_id="cross_strait_relations",
            label="兩岸關係",
            primary=(
                "兩岸",
                "中共",
                "中國大陸",
                "陸委會",
                "國台辦",
                "一中原則",
                "九二共識",
                "台海",
                "M503",
            ),
            supporting=(
                "北京",
                "中國",
                "對台",
                "統戰",
                "ECFA",
                "和平統一",
                "台灣參與",
            ),
            exclude=(
                "中國信託",
                "中國鋼鐵",
                "中國醫藥",
            ),
            categories=("politics",),
        ),
        TopicSpec(
            topic_id="foreign_affairs",
            label="外交與國際",
            primary=(
                "外交",
                "外訪",
                "出訪",
                "訪團",
                "邦交國",
                "美中峰會",
                "APEC",
                "G7",
                "聯合國",
                "WHO",
                "WHA",
                "制裁",
                "代表處",
            ),
            supporting=(
                "美國",
                "日本",
                "歐盟",
                "白宮",
                "國務院",
                "友邦",
                "國際",
            ),
            exclude=(
                "校外訪問",
                "企業訪團",
            ),
            categories=("politics",),
        ),
        TopicSpec(
            topic_id="legislative_policy",
            label="立法與政策",
            primary=(
                "立法院",
                "立委",
                "法案",
                "修法",
                "草案",
                "三讀",
                "一讀",
                "委員會審查",
                "質詢",
                "行政院",
                "政策",
            ),
            supporting=(
                "黨團協商",
                "院會",
                "表決",
                "覆議",
                "條例",
                "預算案",
            ),
            exclude=(
                "公司章程修法",
                "校規修法",
            ),
            categories=("politics",),
        ),
        TopicSpec(
            topic_id="party_politics",
            label="政黨政治",
            primary=(
                "民進黨",
                "國民黨",
                "民眾黨",
                "黨主席",
                "黨團",
                "派系",
                "黨紀",
                "藍白",
                "藍綠",
                "政黨",
            ),
            supporting=(
                "黨內",
                "提名",
                "攻防",
                "砲轟",
                "主席選舉",
            ),
            exclude=(
                "派對",
                "公司黨團",
            ),
            categories=("politics",),
        ),
        TopicSpec(
            topic_id="political_accountability",
            label="政治責任與弊案",
            primary=(
                "貪污",
                "弊案",
                "圖利",
                "利益衝突",
                "彈劾",
                "糾正案",
                "監察院",
                "請辭",
                "下台",
                "不適任",
                "失職",
                "官員涉案",
            ),
            supporting=(
                "調查",
                "檢調",
                "政風",
                "約談",
                "起訴",
                "懲處",
                "道歉",
            ),
            exclude=(
                "企業貪污",
                "公司弊案",
            ),
            categories=("politics",),
        ),
        TopicSpec(
            topic_id="defense_security",
            label="國防與安全",
            primary=(
                "國防",
                "軍購",
                "國安",
                "國安法",
                "兵役",
                "徵兵",
                "教召",
                "漢光演習",
                "資安",
                "情資",
                "共機",
                "共艦",
                "解放軍",
                "飛彈",
                "無人機",
            ),
            supporting=(
                "國軍",
                "軍方",
                "台海",
                "中共",
                "威脅",
                "防衛",
                "軍演",
            ),
            exclude=(
                "資安公司",
                "軍購案詐騙",
            ),
            categories=("politics",),
        ),
        TopicSpec(
            topic_id="public_budget",
            label="公共預算",
            primary=(
                "預算",
                "特別預算",
                "總預算",
                "追加預算",
                "補助款",
                "凍結預算",
                "刪減預算",
                "統籌分配款",
                "財政紀律",
                "公共建設",
            ),
            supporting=(
                "中央",
                "地方",
                "立法院",
                "行政院",
                "補助",
                "經費",
                "編列",
                "審查",
            ),
            exclude=(
                "公司預算",
                "家庭預算",
            ),
            categories=("politics",),
        ),
    ]
)
