CREATE DATABASE IF NOT EXISTS `news_relay` CHARACTER SET utf8mb4;
USE `news_relay`;

CREATE TABLE IF NOT EXISTS `t_relay_events` (
  id BIGINT NOT NULL AUTO_INCREMENT,
  event_id VARCHAR(128) NULL,
  source VARCHAR(64) NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  summary TEXT NULL,
  published_at VARCHAR(64) NULL,
  event_hash CHAR(40) NOT NULL,
  raw_json JSON NULL,
  is_pushed TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_event_hash (event_hash),
  KEY idx_push_queue (is_pushed, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `t_bot_group_info` (
  id BIGINT NOT NULL AUTO_INCREMENT,
  group_id VARCHAR(128) NOT NULL,
  test_account TINYINT(1) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_group_id (group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `t_bot_user_info` (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(128) NOT NULL,
  test_account TINYINT(1) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
